#!/usr/bin/sh

# # post, a newsmaker application, entirely written in bash for the
# Newsroom community. 
# It does two things:
# 1. It uses content on the clipboard to create news articles, or a
# set of articles as a draft; and 
# 2. It then compiles those articles into a Newspost electronic
# publication as an ebook. 
# As to which function it does depends on how it is evoked.
#
# Preliminary variables. These variables are called from every
# function of the program:
# Most of these should be set as environment variables, if not, then
# use the following defaults:
progname=$(basename "$0")
NP_HOME="${NP_HOME:=$HOME/.config/npost}"
scriptdir="$NP_HOME/scripts"
NP_NEWSDIR="$HOME/Documents/News"
filename="${NP_NEWSDIR}/tmp"
drafts="${NP_NEWSDIR}/drafts"
category=
article_dir=

usage() {
	firefox "$NP_HOME/manual/manual.html"
	# Bring up the help manual with the --help option
}


# This module creates a news bulletin, depending on which other
# function called it.
make_bulletin() {
# Set important variables for further processing:
# Is the NEWSPOST directory for saving the final epub file set? If
# not, save our stuff to the user's home directory and be done with
# it:
NP_NEWSPOST="${NP_NEWSPOST:=$HOME}"
text="newsroom.md"
declare when
d=$(date +'%A %d %B %Y')
h=$(date +%H)
# Now what time is it?
if [ $h -lt 12  ]
then
	when="Morning"
elif [ $h -lt 18 ]
then 
	when="Afternoon"
else
	when="Evening"
fi

cd $NP_NEWSDIR
awk -v time="$when" -v day="$d" -f $scriptdir/bulletin.awk $filename>$text
cat "$HOME/Templates/Snippets/newspost.txt" >>$text
bulletin="newspost_daily_${d// /_}_${when}_edition"
bulletin="${NP_NEWSPOST}/${bulletin,,}.epub"
# Now convert this bulletin to ebook:
pandoc $text -o $bulletin --split-level=2 && rm $text
}

insert_section_numbers() {
	## This function numbers titles for each category before
	#compilation.
rhdraft="$1"
tpc="${rhdraft}-topics"

# First let us find how many articles are there using the nl utility:
grep '## ' $rhdraft | nl | sed 's/^[[:space:]]\+//' >"$tpc"
sed -i "/## /R $tpc" $rhdraft
sed -i -Ee '
  /## /N
  s/## .*\n(.*)/\1/'  $rhdraft
sed -i 's/^\([[:digit:]]\+\)[[:space:]]\+\(## \)/\2\1. /' $rhdraft
rm $tpc
}


create_single_article() {
	# This function creates individual articles for placemrnt in
	# categories:

	# How many current articles are there for us to add another
	# one?
count=$(ls "$article_dir" 2>/dev/null | wc -l)
count=$(( count + 1))
article="${count}.txt"
sed -i -f $scriptdir/article.sed "$filename"
mv "$filename" "${article_dir}/$article"
}

create_batch_articles()
{
# This function creates a whole news category from clipboard contents
# and saves it to the drafts folder:

# First sanitise the clipboard contents for a news bulletin format using
# sed:
sed -i -f $scriptdir/category.sed $filename

# Now let's initialise our variables:
draft="${drafts}/$category"
initialize_draft
awk -f $scriptdir/category.awk $filename>>$draft
rm $filename
}

classify_clipboard_content() {
# This function inspects clipboard content to determine where it
# should be placed and which other function should be used afterwards:

xclip -sel clip  -r -o >$filename
content=$(head -n2 $filename | tail -1)
if [[ "$content" =~ ^[A-Za-z0-9.-]+\.[A-Za-z]{2,4}$ ]]; then
	create_single_article
elif [[ "$content" == "| | |" ]]; then
	create_batch_articles
else
	echo "This content is not suitable for a Newspost article. Check its format and try again." >&2
	rm $filename
	exit 1
fi
}

check_draft() {
# check whether the passed in argument exists in the 'drafts' folder:

[ -f "$drafts/$category" ]
}

check_files() {
# check whether passed in directory indeed exists:

count=$(ls $article_dir/*.txt 2>/dev/null | wc -l)
[[ $count -gt 0 ]]
}

initialize_draft(){
# this function is called to create a new draft if the name it gets
# does not exist in the drafts directory:
#
local title
if [[ "$category" == "culture" ]]; then
	title="RELIGION AND CULTURE"
elif [[ "$category" == "entertainment" ]]; then
	title="ARTS AND ENTERTAINMENT"
elif [[ "$category" == "technology" ]]; then
	title="SCIENCE AND TECHNOLOGY"
else
title="${category^^}"
fi
! check_draft && echo "# $title">"$drafts/$category"
}

compile_articles() {
	# this function is responsible for preparing the drafts to be
	# used in the bulletin by compiling them from appropriate
	# directories in the news articles:
	files="${article_dir}/*.txt"
draft="$drafts/$category"

if ! check_files; then
check_draft && return
echo "no new articles in '$category' to scan for a draft. add new articles and run this program again." >&2
	exit 1
	else
		initialize_draft
cat $files >>$draft
rm $files
fi
}

put_together () {
	# this is the workhorse of this program: takes whatever
	# argument it receives and compiles a news bulletin using the
	# make_bulletin module:

	# Let us create a set of available categories for compiling
	# this post based on what has been passed to this function
	# rather than using the global NP_CATEGORIES. This helps us to
	# avoid bugs about assuming what is not wanted by the user: so
	# let us define a new array:
	categories=()
	for i in "$@"; do
categorize $i
compile_articles
categories+=($category)
	done

# now read all drafts into the temporary filename:
for p in "${categories[@]}"
do
	post="$drafts/${p}"
	insert_section_numbers "$post"
cat "$post" >>$filename && rm $post
done
# now call the make_bulletin function to compile to epub:
make_bulletin

# and now clean up everything:
rm $filename
}

add_to() {
	# this function simply creates new files as article drafts
	# using the clipboard, and then validate the input:
if [[ -z "$1" ]]; then
	echo "error, you cannot call this function without arguments. you have to provide name of the category to place your articles." >&2
	exit 1
else
	categorize $1
	classify_clipboard_content
fi
}

categorize() {
# Normalize program input shortcuts to full directory names:
# And act as the program's gatekeeper to throw away invalid inputs and
# quit:
case "$1" in
	af) category="africa"
		;;
	bsn) category="business"
		;;
	clt) category="culture"
		;;
	art) category="entertainment"
		;;
	sp) category="sport"
		;;
	tch) category="technology"
		;;
	wrd) category="world"
		;;
	zw) category="zimbabwe"
		;;
	opn) category="opinion";;
	*) category="${1,,}";;
esac 

article_dir="${NP_NEWSDIR}/articles/$category"
# Check whether the category indeed exists, and quit if it does not:
[[ ! -d "$article_dir" ]] && echo "No category '$category' in current Newspost categories." && exit 1
}

## Sanitise the inputs:
clear
# Program cannot run if the $NP_CATEGORIES environment variable is not
# set: check it and exit if not set:
	if [[ -z "$NP_CATEGORIES" ]]; then
		echo "the NP_CATEGORIES environment variable is not set. This program cannot run without it.">&2
		exit 1
	fi

if [[ "$#" -eq 0 ]]; then
	# To lazy to type? Just pass in the categories in the
	# NP_CATEGORIES and be done with it:
put_together $NP_CATEGORIES
else
	case "$1" in
		-a | --add-to) add_to $2 
			;;
		-h | --help)
			usage
			exit
			;;
-* | --*) usage >&2
	exit 1;;
*)
	put_together $@
	esac
fi

